languageCode = "en-us"
title = "Scripture Audio"
baseurl = "https://scriptureaudio.github.io/"
theme = "ghostwriter"
copyright = "2016"
disqusShortname = "scriptureaudio"

[Author]
    name = "ScriptureAudio"
    profile = "https://www.facebook.com/ScriptureAudio-1185573308164019/?ref=bookmarks"

[Taxonomies]
	tag = "tags"

[Params]
	intro = true
	headline = "Scripture Audio"
	description = "'' ... Let the word of Christ dwell in you richly ... '' Col. 3.16"
	twitter = "https://twitter.com/ScriptureAudio"

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Articles"
    url = "/articles/"
    weight = 1

    [[menu.main]]
    name = "Blog"
    url = "/post/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 3

[[menu.main]]
    name = "Heritage"
    url = "/project/heritage/heritage/"
    weight = 4

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 5